openapi: 3.0.3
info:
  title: KIS API
  version: 1.0.0
  description: KIS Backend API Documentation
paths:
  /api/kis/accounts/:
    get:
      operationId: kis_accounts_list
      description: 현재 로그인한 사용자의 KIS 계좌 목록을 조회합니다.
      summary: KIS 계좌 목록 조회
      tags:
      - kis
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KISAccountList'
          description: ''
    post:
      operationId: kis_accounts_create
      description: 새로운 KIS 계좌를 등록합니다.
      summary: KIS 계좌 생성
      tags:
      - kis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KISAccountRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/KISAccountRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/KISAccountRequest'
        required: true
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KISAccount'
          description: ''
  /api/kis/accounts/{id}/:
    get:
      operationId: kis_accounts_retrieve
      description: 특정 KIS 계좌의 상세 정보를 조회합니다.
      summary: KIS 계좌 상세 조회
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - kis
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KISAccount'
          description: ''
    put:
      operationId: kis_accounts_update
      description: KIS 계좌 정보를 전체 수정합니다.
      summary: KIS 계좌 전체 수정
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - kis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KISAccountRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/KISAccountRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/KISAccountRequest'
        required: true
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KISAccount'
          description: ''
    patch:
      operationId: kis_accounts_partial_update
      description: KIS 계좌 정보를 부분 수정합니다.
      summary: KIS 계좌 부분 수정
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - kis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedKISAccountRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedKISAccountRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedKISAccountRequest'
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KISAccount'
          description: ''
    delete:
      operationId: kis_accounts_destroy
      description: KIS 계좌를 삭제합니다.
      summary: KIS 계좌 삭제
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - kis
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '204':
          description: No response body
  /api/kis/accounts/check_exists/:
    get:
      operationId: kis_accounts_check_exists_retrieve
      description: 사용자가 등록한 KIS 계좌가 있는지 확인합니다.
      summary: 계좌 존재 여부 확인
      tags:
      - kis
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KISAccount'
          description: ''
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      security:
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/users/change-password/:
    post:
      operationId: users_change_password_create
      description: |-
        API endpoint for changing password.
        POST /api/users/change-password/
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        required: true
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Password changed successfully
        '400':
          description: Invalid request or wrong password
  /api/users/profile/:
    get:
      operationId: users_profile_retrieve
      description: |-
        API endpoint for viewing and updating user profile.
        GET /api/users/profile/
        PATCH /api/users/profile/
      tags:
      - users
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: users_profile_update
      description: |-
        API endpoint for viewing and updating user profile.
        GET /api/users/profile/
        PATCH /api/users/profile/
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: users_profile_partial_update
      description: |-
        API endpoint for viewing and updating user profile.
        GET /api/users/profile/
        PATCH /api/users/profile/
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserRequest'
      security:
      - jwtAuth: []
      - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/register/:
    post:
      operationId: users_register_create
      description: |-
        API endpoint for user registration.
        POST /api/users/register/
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      security:
      - jwtAuth: []
      - Bearer: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
components:
  schemas:
    ChangePasswordRequest:
      type: object
      description: Serializer for password change.
      properties:
        old_password:
          type: string
          minLength: 1
        new_password:
          type: string
          minLength: 1
      required:
      - new_password
      - old_password
    KISAccount:
      type: object
      description: KIS 계좌 정보 시리얼라이저
      properties:
        id:
          type: integer
          readOnly: true
        account_number:
          type: string
          description: 계좌번호
          maxLength: 20
        account_id:
          type: string
          description: 실계좌 id
          maxLength: 50
        app_key:
          type: string
          maxLength: 36
        sec_key:
          type: string
          maxLength: 180
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - account_id
      - account_number
      - app_key
      - created_at
      - id
      - sec_key
      - updated_at
    KISAccountList:
      type: object
      description: KIS 계좌 목록용 시리얼라이저 (보안 정보 제외)
      properties:
        id:
          type: integer
          readOnly: true
        account_number:
          type: string
          description: 계좌번호
          maxLength: 20
        account_id:
          type: string
          description: 실계좌 id
          maxLength: 50
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - account_id
      - account_number
      - created_at
      - id
      - updated_at
    KISAccountRequest:
      type: object
      description: KIS 계좌 정보 시리얼라이저
      properties:
        account_number:
          type: string
          minLength: 1
          description: 계좌번호
          maxLength: 20
        account_id:
          type: string
          minLength: 1
          description: 실계좌 id
          maxLength: 50
        app_key:
          type: string
          minLength: 1
          maxLength: 36
        sec_key:
          type: string
          minLength: 1
          maxLength: 180
      required:
      - account_id
      - account_number
      - app_key
      - sec_key
    MessageResponse:
      type: object
      description: Serializer for simple message responses.
      properties:
        message:
          type: string
      required:
      - message
    PatchedKISAccountRequest:
      type: object
      description: KIS 계좌 정보 시리얼라이저
      properties:
        account_number:
          type: string
          minLength: 1
          description: 계좌번호
          maxLength: 20
        account_id:
          type: string
          minLength: 1
          description: 실계좌 id
          maxLength: 50
        app_key:
          type: string
          minLength: 1
          maxLength: 36
        sec_key:
          type: string
          minLength: 1
          maxLength: 180
    PatchedUserRequest:
      type: object
      description: Serializer for user profile information.
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
    Register:
      type: object
      description: Serializer for user registration.
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
      required:
      - username
    RegisterRequest:
      type: object
      description: Serializer for user registration.
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          minLength: 1
        password2:
          type: string
          writeOnly: true
          minLength: 1
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
      required:
      - password
      - password2
      - username
    TokenObtainPair:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - refresh
    TokenObtainPairRequest:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - password
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          minLength: 1
      required:
      - refresh
    User:
      type: object
      description: Serializer for user profile information.
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        date_joined:
          type: string
          format: date-time
          readOnly: true
      required:
      - date_joined
      - id
      - username
    UserRequest:
      type: object
      description: Serializer for user profile information.
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
      required:
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
