# Generated by Django 6.0 on 2025-12-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kis_account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KISAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "account_number",
                    models.CharField(help_text="계좌번호", max_length=20, unique=True),
                ),
                ("account_id", models.CharField(help_text="실계좌 id", max_length=50)),
                ("app_key", models.CharField(max_length=36)),
                ("sec_key", models.CharField(max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kis_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KIS Account",
                "verbose_name_plural": "KIS Accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="KISAccounts",
        ),
    ]
